import { Epilogue, Plus_Jakarta_Sans, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
  weight: ["400", "700", "800", "900"],
  style: ["normal", "italic"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  weight: ["400", "500", "600"],
});

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
  weight: ["600"],
});

/** Subset of Material Symbols regenerated by `npm run icons`. */
const icons = localFont({
  src: "./fonts/material-symbols-outlined.woff2",
  variable: "--font-icons",
  display: "block",
});

/** Font CSS variables for <html>, shared by the root layout and the global error page. */
export const FONT_VARIABLES = [epilogue, jakarta, grotesk, icons]
  .map((font) => font.variable)
  .join(" ");
