import type { ReactNode } from "react";
import type { Metadata, Viewport } from "next";
import { Epilogue, Plus_Jakarta_Sans, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "../styles/main.scss";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { getResumeDownload } from "../lib/content";
import { SITE_DESCRIPTION, SITE_NAME, SITE_TITLE, SITE_URL } from "../lib/site";
import { THEME_INIT_SCRIPT } from "../lib/theme";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from '@vercel/analytics/next';

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
  weight: ["400", "700", "800", "900"],
  style: ["normal", "italic"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  weight: ["400", "500", "600"],
});

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
  weight: ["600"],
});

/** Subset of Material Symbols regenerated by `npm run icons`. */
const icons = localFont({
  src: "./fonts/material-symbols-outlined.woff2",
  variable: "--font-icons",
  display: "block",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "/",
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  keywords: [
      "portfolio",
      "C++",
      "C++ developer",
      "C",
      "JavaScript",
      "CUDA",
      "OpenCL",
      "Data visualization",
      "Web development",
  ]
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f9f4e8" },
    { media: "(prefers-color-scheme: dark)", color: "#18181a" },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const resume = await getResumeDownload();

  // The head script sets `data-theme` and `data-js` before hydration, hence
  // `suppressHydrationWarning`.
  return (
    <html
      lang="en"
      className={`${epilogue.variable} ${jakarta.variable} ${grotesk.variable} ${icons.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body>
        <a className="skip-link" href="#main">
          Skip to content
        </a>
        <div className="ambient" aria-hidden="true">
          <div className="ambient-blob ambient-blob-1" />
        </div>

        <Navbar resume={resume} />

        {children}

        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
